baseURL = "http://richardlyon.net/"
languageCode = "en-uk"
title = "Lyon's Field Notes"

[menu]

  [[menu.main]]
    identifier = "About"
    name = "About"
    url = "/about/"

[outputFormats.Algolia]
  baseName = "algolia"
  isPlainText = true
  mediaType = "application/json"
  notAlternative = true

[params.algolia]
  vars = ["title", "summary", "date", "publishdate", "expirydate", "permalink"]
  params = ["categories", "tags"]

[outputs]
  home = ["HTML", "RSS", "Algolia"]
